language: csharp
solution: FreeLauncher.sln
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" FreeLauncher.sln
script:
- xbuild /validate ./src/dotMCLauncher.Core/dotMCLauncher.Core.csproj
- xbuild /validate ./src/dotMCLauncher.Yggdrasil/dotMCLauncher.Yggdrasil.csproj